PROJECT (hello-world)

CMAKE_MINIMUM_REQUIRED(VERSION 2.8)

# Set a default build type if none was specified
if(NOT CMAKE_BUILD_TYPE AND NOT CMAKE_CONFIGURATION_TYPES)
  message("Setting build type to 'RelWithDebInfo' as none was specified.")
  set(CMAKE_BUILD_TYPE RelWithDebInfo CACHE STRING "Choose the type of build." FORCE)
  # Set the possible values of build type for cmake-gui
  set_property(CACHE CMAKE_BUILD_TYPE PROPERTY STRINGS "Debug" "Release"
    "MinSizeRel" "RelWithDebInfo")
endif()

message(STATUS "PROJECT_NAME=" ${PROJECT_NAME})
message(STATUS "PROJECT_BINARY_DIR=" ${PROJECT_BINARY_DIR})
message(STATUS "PROJECT_SOURCE_DIR=" ${PROJECT_SOURCE_DIR})

message(STATUS "CMAKE_MAJOR_VERSION=" ${CMAKE_MAJOR_VERSION})
message(STATUS "CMAKE_MINOR_VERSION=" ${CMAKE_MINOR_VERSION})
message(STATUS "CMAKE_PATCH_VERSION=" ${CMAKE_PATCH_VERSION})

message(STATUS "CMAKE_SYSTEM=" ${CMAKE_SYSTEM})
message(STATUS "CMAKE_SYSTEM_NAME=" ${CMAKE_SYSTEM_NAME})
message(STATUS "CMAKE_SYSTEM_VERSION=" ${CMAKE_SYSTEM_VERSION})
message(STATUS "CMAKE_SYSTEM_PROCESSOR=" ${CMAKE_SYSTEM_PROCESSOR})

SET(CMAKE_MODULE_PATH ${PROJECT_SOURCE_DIR}/cmake)
ADD_DEFINITIONS(-DENABLE_DEBUG -DABC)
#set (CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -DEX2" CACHE STRING "Set C++ Compiler Flags" FORCE)
message(STATUS "CMAKE_MODULE_PATH=" ${CMAKE_MODULE_PATH})
message(STATUS "CMAKE_C_FLAGS=" ${CMAKE_C_FLAGS})
message(STATUS "CMAKE_CXX_FLAGS=" ${CMAKE_CXX_FLAGS})
ADD_SUBDIRECTORY (src)
